contact_links:
  - about: Ask a question or request support here
    name: Ask for Support
    url: >-
      https://github.com/ZeDon-SP/ssdcoin-blockchain/discussions/new?category=support
  - about: Request a new feature or idea here
    name: Make a Request
    url: >-
      https://github.com/ZeDon-SP/ssdcoin-blockchain/discussions/new?category=ideas
